# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MVC

  target 'MVCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'AFNetworking'
  pod 'Masonry'
  pod 'SVProgressHUD'
  pod 'YYModel'

end
