# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RAC实现的MVVM' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RAC实现的MVVM

  target 'RAC实现的MVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RAC实现的MVVMUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  use_frameworks!
  pod 'ReactiveObjC'

end
